# Generated by Django 4.2 on 2023-04-05 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('condition', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=4)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_main.company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_main.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in', models.DateTimeField(blank=True, null=True)),
                ('checked_out', models.DateTimeField(auto_now_add=True)),
                ('condition_in', models.CharField(blank=True, choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=4, null=True)),
                ('condition_out', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=4)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_main.device')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_main.employee')),
            ],
        ),
    ]
